#!/bin/sh
# SDAD v6 -- I1 evidence acquisition (HYBRID STUB, BR-17). POSIX mirror of
# acquire-evidence.ps1. ASCII (L-01). Emits node-graph.json + manifest.md that
# DECLARE the un-acquired model as a gap (status not_assessable). NEVER fabricates
# a node graph; NEVER crashes on a missing/unparseable export.
#   .ppl parse is a documented STUB (format unverified) -- declared not_assessable.
#
# Usage:
#   sh .sdad/audit/lib/acquire-evidence.sh PROJECT [PPL_PATH] [OUT_DIR]
project="$1"
ppl="$2"
outdir="$3"
if [ -z "$project" ]; then echo "acquire-evidence: PROJECT argument required"; exit 1; fi
if [ -z "$outdir" ]; then outdir=".sdad/audit/$project/evidence"; fi
mkdir -p "$outdir"

date_str=$(date +%Y-%m-%d)

if [ -n "$ppl" ]; then
  acq="ppl-export"
  if [ -f "$ppl" ]; then
    # TODO(BR-17): implement .ppl parsing once the format is verified against a
    # real Pyplan export. Until then a supplied .ppl is declared not_assessable.
    gap_area=".ppl parse"
    gap_reason="parser stub not implemented (BR-17): .ppl format unverified, no real fixture"
  else
    gap_area=".ppl parse"
    gap_reason="supplied .ppl path not found: $ppl"
  fi
else
  acq="manual"
  gap_area="model acquisition"
  gap_reason="no .ppl export and no MCP read supplied; populate node-graph.json manually or via pyplan-mcp"
fi

cat > "$outdir/node-graph.json" <<JSON
{
  "project": "$project",
  "acquired_at": "$date_str",
  "acquisition_path": "$acq",
  "pyplan_version": "unknown",
  "nodes": [],
  "gaps": [
    { "area": "$gap_area", "reason": "$gap_reason", "status": "not_assessable" }
  ]
}
JSON

cat > "$outdir/manifest.md" <<MD
# Evidence Manifest -- $project

- Acquired at: $date_str
- Acquisition path: $acq
- Pyplan version: unknown
- Nodes acquired: 0

## Declared gaps (not assessable)
- [$gap_area] $gap_reason

Generated by .sdad/audit/lib/acquire-evidence.sh (I1 hybrid stub, BR-17).
MD

echo "acquire-evidence: wrote $outdir/node-graph.json and $outdir/manifest.md"
echo "acquire-evidence: 1 gap(s) declared not_assessable"
exit 0
