# SDAD v6 -- I1 evidence acquisition (HYBRID STUB, BR-17). ASCII (L-01).
# Acquires a Pyplan model representation for $audit. Priority order:
#   (a) .ppl export parse  -> STUB: format unverified, NOT IMPLEMENTED (see TODO)
#   (b) Pyplan MCP read    -> handled by the auditor via the pyplan-mcp skill, not here
#   (c) manual fallback    -> developer supplies node-graph.json directly
# This stub NEVER crashes on a missing or unparseable export: it emits an
# evidence manifest + node-graph.json that DECLARES the un-acquired area as a
# gap (status not_assessable), per the brief's honesty rule. It NEVER fabricates
# a node graph. Mirror: acquire-evidence.sh
#
# Usage:
#   powershell -File .sdad\audit\lib\acquire-evidence.ps1 -Project NAME [-PplPath model.ppl] [-OutDir dir]
param(
    [Parameter(Mandatory=$true)][string]$Project,
    [string]$PplPath,
    [string]$OutDir
)
$ErrorActionPreference = "Stop"

if (-not $OutDir) { $OutDir = Join-Path ".sdad/audit/$Project" "evidence" }
New-Item -ItemType Directory -Path $OutDir -Force | Out-Null

$gaps = New-Object System.Collections.ArrayList
$acqPath = "manual"

if ($PplPath) {
    $acqPath = "ppl-export"
    if (Test-Path $PplPath) {
        # TODO(BR-17): implement .ppl parsing once the format is verified against a
        # real Pyplan export. Until then a supplied .ppl is declared not_assessable
        # rather than parsed with a guessed format. Do NOT fake a node graph here.
        [void]$gaps.Add([ordered]@{
            area = ".ppl parse"
            reason = "parser stub not implemented (BR-17): .ppl format unverified, no real fixture"
            status = "not_assessable"
        })
    } else {
        [void]$gaps.Add([ordered]@{
            area = ".ppl parse"
            reason = "supplied .ppl path not found: $PplPath"
            status = "not_assessable"
        })
    }
} else {
    [void]$gaps.Add([ordered]@{
        area = "model acquisition"
        reason = "no .ppl export and no MCP read supplied; populate node-graph.json manually or via pyplan-mcp"
        status = "not_assessable"
    })
}

$dateStr = (Get-Date).ToString("yyyy-MM-dd")

# Build node-graph.json. nodes is intentionally empty here -- the stub acquired
# none; the gap explains why. Serialize the empty array explicitly so the
# validator sees [] and not null.
$nodesJson = "[]"
$gapsJson = ($gaps | ConvertTo-Json -Depth 5)
if ($gaps.Count -eq 1) { $gapsJson = "[" + $gapsJson + "]" }  # PS unwraps single-element arrays

$graphText = @"
{
  "project": "$Project",
  "acquired_at": "$dateStr",
  "acquisition_path": "$acqPath",
  "pyplan_version": "unknown",
  "nodes": $nodesJson,
  "gaps": $gapsJson
}
"@

$graphPath = Join-Path $OutDir "node-graph.json"
Set-Content -Path $graphPath -Value $graphText -Encoding ASCII

# manifest.md
$lines = New-Object System.Collections.ArrayList
[void]$lines.Add("# Evidence Manifest -- $Project")
[void]$lines.Add("")
[void]$lines.Add("- Acquired at: $dateStr")
[void]$lines.Add("- Acquisition path: $acqPath")
[void]$lines.Add("- Pyplan version: unknown")
[void]$lines.Add("- Nodes acquired: 0")
[void]$lines.Add("")
[void]$lines.Add("## Declared gaps (not assessable)")
foreach ($gp in $gaps) { [void]$lines.Add("- [$($gp.area)] $($gp.reason)") }
[void]$lines.Add("")
[void]$lines.Add("Generated by .sdad/audit/lib/acquire-evidence.ps1 (I1 hybrid stub, BR-17).")

$manifestPath = Join-Path $OutDir "manifest.md"
Set-Content -Path $manifestPath -Value ($lines -join "`r`n") -Encoding ASCII

Write-Host "acquire-evidence: wrote $graphPath and $manifestPath"
Write-Host "acquire-evidence: $($gaps.Count) gap(s) declared not_assessable"
exit 0
